---
- name: check or create nginx configs directory
  file: 
    path: "~/nginx/"
    state: "directory"

- name: Write nginx init conf file
  template: 
    src: "nginx.conf"
    dest: "~/nginx/nginx.conf"
    force: yes
  vars:
    nginx_config_type: init

- name: copying project files
  become: true 
  copy:
    src: "{{ role_path }}/files/"
    dest: "~/nginx/"      
    mode: 0755

- name: down previous config
  shell:
    cmd: docker-compose down
    chdir: ~/nginx

- name: remove old data
  shell:
    cmd: rm -rf data
    chdir: ~/nginx

- name: Write nginx init conf file
  template: 
    src: "init-letsencrypt.sh"
    dest: "~/nginx/init-letsencrypt.sh"
    force: yes

- name: start nginx with docker-compose and get certs
  become: yes
  shell: 
    cmd: bash init-letsencrypt.sh
    chdir: ~/nginx
  register: stdout

- name: debug stdout
  debug:
    msg: "{{ stdout }}"

- name: Write nginx init conf file
  template: 
    src: "nginx.conf"
    dest: "~/nginx/nginx.conf"
    force: yes
  vars:
    nginx_config_type: use

- name: start nginx with docker-compose for use
  become: yes
  shell: 
    cmd: docker-compose up -d --force-recreate
    chdir: ~/nginx